### ISSUE TITLE
sendGetGroupsParticipants() error!

### ISSUE THREAD

**Issue by moosaviamir** [venomous0x/WhatsAPI#1105]
I am trying to get Group Participants but when i try the following code:
```
function onParticipants($mynumber, $groupId, $participants)
{
    echo "Group $groupId has the following members:\r\n";
    var_dump($participants);
}

$w->eventManager()->bind("onGetGroupParticipants", "onParticipants");
$w->sendGetGroupsParticipants("***************-1422737928");

for($i = 0; $i < 5; $i++) {
    $w->pollMessage();
}
```
I get this response : 
```
tx  <iq id="getgroupparticipants-1423817586-1" type="get" xmlns="w:g" to="**********-1422737928@g.us">
tx    <list></list>
tx  </iq>


Fatal error: Uncaught exception 'Exception' with message 'Socket closed' in C:\xampp\htdocs\WA\src\whatsprot.class.php:2650 Stack trace: #0 C:\xampp\htdocs\WA\src\whatsprot.class.php(484): WhatsProt->readStanza() #1 C:\xampp\htdocs\WA\src\whatsprot.class.php(1431): WhatsProt->pollMessage() #2 C:\xampp\htdocs\WA\src\whatsprot.class.php(719): WhatsProt->waitForServer('getgrouppartici...') #3 C:\xampp\htdocs\WA\src\t2.php(18): WhatsProt->sendGetGroupsParticipants('*********-14...') #4 {main} thrown in C:\xampp\htdocs\WA\src\whatsprot.class.php on line 2650
```

**Comment by mgp25** [comment]
This repo is outdated! Use WhatsAPI Official instead: https://github.com/mgp25/WhatsAPI-Official

Regards

**Comment by moosaviamir** [comment]
I don't Think so! I just downloaded whatsapi several days ago. 
So you say my Whatsprot.php is out dated?

Regards

**Comment by mgp25** [comment]
You are using WhatsAPI code not WhatsAPI Official one! You should look there, that function you are using is deprecated.

Regards

**Comment by moosaviamir** [comment]
mpg25
Thanks but the official one says :
Fatal error: Call to undefined method WhatsProt::sendGetGroupsParticipants() in C:\xampp\htdocs\WAO\src\t2.php on line 18

Regards

**Comment by mgp25** [comment]
Why you dont read the wiki? Its explained there, search for send get groupv2 info.

Search for that in the code, and you will find the function

**Comment by moosaviamir** [comment]
Ok sorry to bother you! :) I'll figure it out.
Thank you

**Comment by moosaviamir** [comment]
Dear mpg25
Now I get this debug on send get groupv2:
```
tx  <iq id="get_groupv2_info-1423830351-1" xmlns="w:g2" type="get" to="*************-1422737928@g.us">
tx    <query request="interactive"></query>
tx  </iq>


Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\xampp\htdocs\WAO\src\whatsprot.class.php:617 Stack trace: #0 C:\xampp\htdocs\WAO\src\t2.php(21): WhatsProt->pollMessage() #1 {main} thrown in C:\xampp\htdocs\WAO\src\whatsprot.class.php on line 617
```

**Comment by mgp25** [comment]
Update the whole code not only whatsprot.class.php and ask better in WhatsAPI Official issues

**Comment by moosaviamir** [comment]
Ok.
Thank you!
