### ISSUE TITLE
Api show Login Failure with every no and password 

### ISSUE THREAD

**Issue by abhayendra** [venomous0x/WhatsAPI#1131]
tx  <stream:features></stream:features>

tx  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="WAUTH-2" user="91xxxxxxxxxx"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>X/Acò(ˆ´Noý“:ÕÕbá</challenge>

tx  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">—"ã‘÷0Ÿ‹ÜðEañË€«x¢¾»ï'ÌjQÁ-Ã²¶ci</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in E:\www\htdocs\a\src\whatsprot.class.php:1640 Stack trace: #0 E:\www\htdocs\a\src\whatsprot.class.php(474): WhatsProt->doLogin() #1 E:\www\htdocs\a\index.php(8): WhatsProt->loginWithPassword('wQv94uokWkMwKB8...') #2 {main} thrown in E:\www\htdocs\a\src\whatsprot.class.php on line 1640

**Comment by mgp25** [comment]
@abhayendra use WhatsAPI Official... https://github.com/mgp25/WhatsAPI-Official

**Comment by abhayendra** [comment]
hi 
use this code but not work show error 
Error: There was an error with the AJAX request. XML/Json format is bad.

and  on request response return 
Notice: Undefined index: id in E:\www\htdocs\api\examples\whatsapp.php on line 321
{"success":false,"type":"contacts","errormsg":""}

**Comment by mgp25** [comment]
Not this one, go to WhatsAPI Official repo -> https://github.com/mgp25/WhatsAPI-Official

**Comment by abhayendra** [comment]
use this repo but also show this error 
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="917408363533"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>cš\ÂÃËŠÁoÐ6»jt«®–$</challenge>

tx  <response>Ý`gñkw¾Ì£ðõ1ñ±ãë$¨§ò/¬ Ì àÆX1ðÈB7)</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in E:\www\htdocs\api\src\whatsprot.class.php:2304 Stack trace: #0 E:\www\htdocs\api\src\whatsprot.class.php(562): WhatsProt->doLogin() #1 E:\www\htdocs\api\index.php(8): WhatsProt->loginWithPassword('wQv94uokWkMwKB8...') #2 {main} thrown in E:\www\htdocs\api\src\whatsprot.class.php on line 2304

**Comment by mgp25** [comment]
@abhayendra i recommend you openning issues in WhatsAPI Official, not here please.

Use `blockChecker.php` to check if your number its blocked
