### ISSUE TITLE
Contact Sync Problem

### ISSUE THREAD

**Issue by blueslmj** [venomous0x/WhatsAPI#850]
I get these errors when I sync the contacts:

```
Fatal error: Uncaught exception 'Exception' with message 'Tree length did not match received length (buff = 4577 & treeLength = 18626)' in /var/www/whatsprot.class.php:2545
Stack trace:
#0 /var/www/whatsprot.class.php(494): WhatsProt->readStanza()
#1 /var/www/sync.php(93): WhatsProt->pollMessages()
#2 {main}
  thrown in /var/www/whatsprot.class.php on line 2545
```

Anyone can help?  Thanks!

**Comment by best-tech** [comment]
Fatal error</b>:  Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 22 &amp; treeLength = 25)' in /var/www/ph136678/data/www/w.all1c.pro/src/whatsprot.class.php:3716

how can i fix it?

**Comment by mgp25** [comment]
@shirioko use https://github.com/WHAnonymous/Chat-API

**Comment by mgp25** [comment]
@kharchenkodenis use https://github.com/WHAnonymous/Chat-API

**Comment by best-tech** [comment]
it error from there
