### ISSUE TITLE
Password and identity extractor utility for iPhone users

### ISSUE THREAD

**Issue by mgp25** [venomous0x/WhatsAPI#871]
**UPDATE**: [C# utility easier to use](https://github.com/venomous0x/WhatsAPI/issues/871#issuecomment-53996205)

This is a python utility to extract password and identity of WA for iPhone users.

--> Before you use it, you should read this: [https://mgp25.com/blog/utilidadiPhone/](https://mgp25.com/blog/utilidadiPhone/)

Im only going to answer question related to API and usage of the utility. Please, if you have coding question use google :)

**Note:** If you haven't updated iOS or restored firmware, you probably can find this data opening the Cache.db (SQLite3 format).

**Note 2:** If you delete pw.dat and Cache.db (using ssh or iFile..). And open the WhatsApp app, it will ask you for register and verificate your number, once you do this, exit the app, and run this utility.

**Note 3:**
- Host: Your IP (wifi)
- username: If not changed, root
- Password: if not changed, alpine
  Hope you like it!

``` python
# -*- coding: utf-8 -*-
import sqlite3
import paramiko
import os, sys, time

def find_between( s, first, last ):
    try:
        start = s.index( first ) + len( first )
        end = s.index( last, start )
        return s[start:end]
    except ValueError:
        return ""


def getPath(username, host, password):
    dssh = paramiko.SSHClient()
    dssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    dssh.connect(host, username=username, password=password)
    cmd1 = "find /var/mobile/Applications -iname WhatsApp.app"
    print "> "+cmd1
    stdin, stdout, stderr = dssh.exec_command(cmd1)
    res = stdout.read()
    res = res.split("\n")
    print res[0]
    dssh.close()
    return res[0]

def getDB(WAPath, username, host, password):
    localPath = "Cache.db"
    remotePath = WAPath+"/Library/Caches/net.whatsapp.WhatsApp/Cache.db"
    pwFile = WAPath+"/Library/pw.dat"
    transport = paramiko.Transport((host, 22))
    transport.connect(username = username, password = password)
    sftp = paramiko.SFTPClient.from_transport(transport)
    sftp.get(remotePath, localPath)
    sftp.get(pwFile, 'pw.dat')
    sftp.close()
    transport.close()
    print "\n\n- Cache.db downloaded!"
    print "- pw.dat downloaded!"

def getData():
    conn = sqlite3.connect('Cache.db')

    cursor = conn.cursor()

    cursor.execute("SELECT request_key FROM cfurl_cache_response")
    request_key = cursor.fetchall()
    request_key = request_key[0]

    cc = find_between(request_key[0], "cc=", "&")
    pn = find_between(request_key[0], "in=", "&")
    id = find_between(request_key[0], "id=", "&")
    lg = find_between(request_key[0], "lg=", "&")
    lc = find_between(request_key[0]+".", "lc=", ".")

    print "cc: "+cc
    print "pn: "+pn
    print "id: "+id
    print "lg: "+lg
    print "lc: "+lc
    print "\nRequest url: "+request_key[0]

    cursor.execute("SELECT receiver_data FROM cfurl_cache_receiver_data")
    receiver_data = cursor.fetchall()
    receiver_data = receiver_data[0]
    status = find_between(str(receiver_data[0]), "status\":\"", "\"")
    login = find_between(str(receiver_data[0]), "login\":\"", "\"")
    pw = find_between(str(receiver_data[0]), "pw\":\"", "\"")
    type = find_between(str(receiver_data[0]), "type\":\"", "\"")
    expiration = find_between(str(receiver_data[0]), "expiration\":", ",")
    kind = find_between(str(receiver_data[0]), "kind\":\"", "\"")

    print "\nstatus: "+status
    print "login: "+login
    print "pw: "+pw
    print "type: "+type
    print "expiration: "+expiration
    print "kind: "+kind

print '''
###########################################
#                                         #
#    WA Password and Identity Extractor   #
#              for iPhone                 #
#                                         #
###########################################

Author: @_mgp25 - github.com/mgp25 - mgp25.com

''' 
if len(sys.argv) < 4:
    sys.exit("Usage: python extractPW.py <username> <host> <password>\n")
time.sleep(2)
username = sys.argv[1]
host = sys.argv[2]
password = sys.argv[3]
WAPath = getPath(username, host, password)
WAPath = WAPath[0:61]
getDB(WAPath, username, host, password)
print "\n- Extracting data...\n"
getData()
```

Output should be like this:

```
> find /var/mobile/Applications -iname WhatsApp.app
/var/mobile/Applications/3C***59-6**E-4**2-9**9-23B1****B521/WhatsApp.app


- Cache.db downloaded!
- pw.dat downloaded!

- Extracting data...

cc: 34
pn: *********
id: %1F%**%E7%57%**%A8%**%26%**%4F%35%**%B1%69%AF%**
lg: es
lc: ES

Request url: https://v.whatsapp.net/v2/exist?cc=34&in=*********&id=%1F%**%E7%57%**%A8%**%26%**%4F%35%**%B1%69%AF%**&lg=es&lc=ES

status: ok
login: 34*********
pw: ***L9Oxdk***Nh6Hl***jR***Es=
type: existing
expiration: 4444444444.0
kind: free
```

**Comment by jessereitsma** [comment]
Hey

With the python script my return is:
```
- Cache.db downloaded!
- pw.dat downloaded!

- Extracting data...

Traceback (most recent call last):
  File "whatsapp.py", line 103, in <module>
    getData()
  File "whatsapp.py", line 47, in getData
    request_key = request_key[0]
IndexError: list index out of range
```
I'm not really into python, so I don't know how to fix. 
Anyone does know? :)

**Comment by refaei** [comment]
there is no pw.dat in iPhone files WhatsApp app folder where can I find it
